#!/bin/sh

sandbox=".venv"
vbin="$sandbox/bin"
python="python2.7"
ports="7011 7012"
appname="crubadan_clld"
ini="production.ini"
deps="virtualenv python2.7"
datadir="/data/crubadan-clld"
dbfile="clld-db.sqlite"
