#!/bin/bash

sandbox=".venv"
vbin="$sandbox/bin"

ports="7011 7012"
appname="crubadan_clld"
ini="production.ini"

python="python2.7"
deps="virtualenv $python wget"

datadir="/data/crubadan-clld"
dbfile="clld-db.sqlite"

glottodir="$datadir/glottolog"
glottoCSV="$glottodir/languoid.csv"
glottoURL="http://glottolog.org/static/download/glottolog-languoid.csv.zip"
